### ISSUE TITLE
Copy Paste Error - Rolebinding

### ISSUE THREAD

**Issue by fabio-stix-k-business** [SSHcom/privx-kube#65]
Hello, 
we found the following error: 

https://github.com/SSHcom/privx-kube/blob/main/charts/privx/templates/rolebinding.yaml
`Line 18:  name: {{ $subject.kind }}`

should be: 
`Line 18:  name: {{ $subject.name }}`

Kind regards

KBC

**Comment by izareenssh** [comment]
Thanks @fabio-stix-k-business for pointing out the issue. This has now been fixed for the supported PrivX versions.
